### ISSUE TITLE
magit-process buffer waiting on input

### ISSUE THREAD

**Issue by mnsanghvi** [qoocku/magit-p4#3] opened 2016-06-21 23:19 UTC
I did the following in magit:
- staged a change (s)
- committed the change (c c)
- magit-p4-rebase (? 4 r)
- magit-p4-submit (? 4 S s)

and I end up with something like this in the magit-process buffer:

``` emacs
run git … p4 submit
refs/heads/master
Perforce checkout for depot path //perforce/depot/foo/bar/ located at /Users/msanghvi/Work/P4-Repos/depot-foo-bar/
Synchronizing p4 checkout...
... - file(s) up-to-date.
Applying 9d8c2b7 ROAD-2019:
//perforce/depot/foo/bar/module/sub-module/some-script.sh#5 - opened for edit
Waiting for Emacs...
Submit template unchanged. Submit anyway? [y]es, [n]o (skip this patch) 

```

Where it says "Waiting for Emacs..."  I got a buffer with everything related to the P4 submit in it.  I 'C-x #' out of that, and than it just waits on the "Submit template unchanged .... "   waiting for a response.

This is one situation where this has occurred.  It occurred earlier today as well where I had 21 files that I was submitting and it seemed there was some sort of error when patching the files that were opened for edit on the Perforce side.  Again it was waiting for input basically, on how to proceed.  

Pressing y, just takes me to some other buffer, rather than acknowledging that I responded.

Maybe these sort of questions should appear in the mini-buffer and await a response there ?

**Comment by lexa** [comment] 2016-06-22 11:19
Thanks for reporting the issue.
The problem is that git-p4 is trying to be interactive unlike other git tools, but magit is not ready to handle interactive requests from git.

I'll try to make a workaround for this issue, but the real fix should be done in git-p4.

**Comment by lexa** [comment] 2016-06-22 11:24
As temporally workaround you may set git config option  'git-p4.skipSubmitEditCheck' to true.

**Comment by mnsanghvi** [comment] 2016-06-22 11:37
Thanks.  I will try that out and see how that works.

On Wed, Jun 22, 2016 at 7:24 AM, lexa notifications@github.com wrote:

> As temporally workaround you may set git config option
> 'git-p4.skipSubmitEditCheck' to true.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/qoocku/magit-p4/issues/3#issuecomment-227715514, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABpYyMbsd0n_B4dtix_1rXuJUmc4yMfiks5qORtvgaJpZM4I7RI7
> .

## 

Mehul N. Sanghvi
email: mehul.sanghvi@gmail.com

**Comment by lexa** [comment] 2016-06-27 13:36
@mnsanghvi 

Issue should be fixed by now. Could you please check if recent magit-p4 works for you with 'git-p4.skipSubmitEditCheck' set to False ? 

If issue still persists, feel free to reopen the issue.

**Closed as completed by lexa** 2016-06-27 13:36 UTC
